# 使用 .NET Core SDK 作為基礎鏡像
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env
WORKDIR /app

# 複製專案文件
COPY . ./

# 還原 NuGet 套件
RUN dotnet restore

# 建置應用程式
RUN dotnet publish -c Release -o out

# 使用 .NET Core Runtime 作為最終鏡像
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build-env /app/out .

# 設定資料庫連接字串
ENV CONNECTION_STRING="Server=192.168.0.158;Database=web_design;User ID=Web;Password=0519;TrustServerCertificate=true"
# 啟動應用程式
ENTRYPOINT ["dotnet", "webapi_order_system.dll", "--connectionstring=${CONNECTION_STRING}"]